#!/bin/bash
echo "Enter a number"
read num

temp=$num

while [ $temp -ne 0 ]
do 
	rev=$rev$((temp%10))
	temp=$((temp/10))
done

if(($rev==$num))
then
	echo "Palindrome"

else
	echo "Not palindrome"
fi
