#!/bin/bash
echo "enter a year"
read year

if((year%400==0))
then
	echo "It is a leap year"
elif((year%100!=0))
then	
	echo "It is a leap year"
elif((year%4==0))
then	
	echo "It is a leap year"
else
	echo "Not a leap year"
fi
